# 0 Introduction a Pandas

Pandas is an open source library that provides easy-to-use data structures and data analysis tools for the Python programming language.

Further reading:
- [Pandas homepage](https://pandas.pydata.org)

<https://www.w3schools.com/python/pandas/default.asp>

<https://aprendeconalf.es/docencia/python/manual/pandas/>

The main features of this library are:

* It defines new data structures based on the arrays of the NumPy library but with new features.
* It allows to easily read and write files in CSV format, Excel and SQL databases.
* Allows data to be accessed using indexes or names for rows and columns.
* It offers methods to reorder, split, and combine data sets.
* Allows you to work with time series.
* It performs all these operations very efficiently.

In [2]:
# Pandas is usually imported under the pd alias.
import pandas as pd
print(pd.__version__)

2.3.2

# 1 Tipos de datos en Panda

Pandas dispone de tres estructuras de datos diferentes:

   * Series: Estructura de una dimensión.
   * DataFrame: Estructura de dos dimensiones (tablas).
   * Panel: Estructura de tres dimensiones (cubos).

Estas estructuras se construyen a partir de arrays de la librería NumPy, añadiendo nuevas funcionalidades.

# 2 Why use Pandas and what can Pandas do?

Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.
:}

Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.
What Can Pandas Do?

Pandas gives you answers about the data. Like:

    Is there a correlation between two or more columns?
    What is average value?
    Max value?
    Min value?

Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

# 3 Series
A Pandas Series is like a column in a table.
It is a one-dimensional array holding data of any type.

## 3.1 Basic creation of Series

In [40]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

In [41]:
#If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

#This label can be used to access a specified value.

myvar[1]

np.int64(7)

## 3.2 Using label / Index

In [5]:
#With the index argument, you can name your own labels.

In [42]:
a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [43]:
#When you have created labels, you can access an item by referring to the label or to the index number
print(myvar["y"])
print(myvar[1])

7
7

/var/folders/yr/t_hh52ln6c74pgk0whp3l7y80000gn/T/ipykernel_44673/354953187.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(myvar[1])

## 3.3 Create Serie using lists

In [44]:

import pandas as pd
datos=['Álgebra', 'Cáculo', 'Python', 'Visualización', 'Inglés']
indices=["Asig 1", "Asig 2", "Asig 3", "Asig 4", "Asig 5"]
s=pd.Series(data=datos, index=indices, dtype='string')
#Alternative
#s=pd.Series(datos, indices, dtype='string')
print(s)

Asig 1          Álgebra
Asig 2           Cáculo
Asig 3           Python
Asig 4    Visualización
Asig 5           Inglés
dtype: string

In [45]:
#Compare diferences
s2=pd.Series(datos)
print(s2)

0          Álgebra
1           Cáculo
2           Python
3    Visualización
4           Inglés
dtype: object

In [46]:
print(s.values)

<StringArray>
['Álgebra', 'Cáculo', 'Python', 'Visualización', 'Inglés']
Length: 5, dtype: string

In [11]:
print(s.index)

Index(['Asig 1', 'Asig 2', 'Asig 3', 'Asig 4', 'Asig 5'], dtype='object')

In [12]:
print(s2.values)

['Álgebra' 'Cáculo' 'Python' 'Visualización' 'Inglés']

In [13]:
print(s2.index)

RangeIndex(start=0, stop=5, step=1)

## 3.4 Create Serie using dictionaries

In [47]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [15]:
datos={'Matemáticas':6.0, 'Economía':4.5,'Programación': 8.5}
s=pd.Series(data=datos)
print(s)

Matemáticas     6.0
Economía        4.5
Programación    8.5
dtype: float64

In [16]:
#To select only some of the items in the dictionary, use the index argument and specify only
#the items you want to include in the Series.
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

## 3.5 Create Serie Numpy array

In [57]:
import numpy as np
serie = pd.Series(np.random.randn(10))
print(type(serie))
print(serie)

<class 'pandas.core.series.Series'>
0    0.519929
1    0.126033
2   -1.462692
3    1.855584
4    0.398833
5   -0.956705
6   -0.573233
7   -2.150492
8   -1.226052
9    1.253527
dtype: float64

## 3.6 Create serie with dates as index

In [18]:
serie = pd.Series(np.random.randn(28), index = pd.date_range('2018/02/01', periods = 28))
print('Serie temporal con índices de fechas \n{} \n'.format(serie))
print(type(serie))

Serie temporal con índices de fechas
2018-02-01   -0.033465
2018-02-02    0.409336
2018-02-03    0.582502
2018-02-04   -0.542151
2018-02-05   -0.782506
2018-02-06    1.858212
2018-02-07    0.136663
2018-02-08    1.511165
2018-02-09    1.263572
2018-02-10    0.585847
2018-02-11    0.033717
2018-02-12   -1.263120
2018-02-13    1.360740
2018-02-14    1.875736
2018-02-15   -0.385643
2018-02-16    0.036376
2018-02-17   -0.921398
2018-02-18    0.275953
2018-02-19   -0.145827
2018-02-20    0.548083
2018-02-21    0.377124
2018-02-22    0.840544
2018-02-23    0.500779
2018-02-24    0.159434
2018-02-25   -1.282860
2018-02-26   -0.912127
2018-02-27   -1.131377
2018-02-28   -1.902672
Freq: D, dtype: float64

<class 'pandas.core.series.Series'>

## 3.7 Properties of Series

In [58]:
datos={'Matemáticas':6.0, 'Economía':4.5,'Programación': 8.5}
s = pd.Series(datos)
print(s.size)
print(s.values)
print(s.index)
s.dtype

type(s)

#1.- s.size: Devuelve el número de elementos de la serie s.
#2.- s.index: Devuelve una lista con los nombres de las filas de la serie s.
#3.- s.values: Devuelve una lista con los valores de la serie DataFrame s.
#4.- s.dtype: Devuelve el tipo de datos de los elementos de la serie s

3
[6.  4.5 8.5]
Index(['Matemáticas', 'Economía', 'Programación'], dtype='object')

pandas.core.series.Series

## 3.8 Summary of functions with series

In [20]:
#Resumen descriptivo de una serie
#Las siguientes funciones permiten resumir varios aspectos de una serie:
#s.count() : Devuelve el número de elementos que no son nulos ni NaN en la serie s.
#s.sum() : Devuelve la suma de los datos de la serie s cuando los datos son de un tipo numérico, o
#la concatenación de ellos cuando son del tipo cadena str.
#s.cumsum() : Devuelve una serie con la suma acumulada de los datos de la serie s cuando los datos son de un tipo numérico.
#s.value_counts() : Devuelve una serie con la frecuencia (número de repeticiones) de cada valor de la serie s.
#s.min() : Devuelve el menor de los datos de la serie s.
#s.max() : Devuelve el mayor de los datos de la serie s.
#s.mean() : Devuelve la media de los datos de la serie s cuando los datos son de un tipo numérico.
#s.std() : Devuelve la desviación típica de los datos de la serie s cuando los datos son de un tipo numérico.
#s.describe(): Devuelve una serie con un resumen descriptivo que incluye el número de datos,
# su suma, el mínimo, el máximo, la media, la desviación típica y los cuartiles.
#


print(s.count())
print(s.sum())
print(s.cumsum())
print(s.value_counts())
print(s.min())
print(s.max() )
print(s.mean())
print(s.std())
print(s.describe())

3
19.0
Matemáticas      6.0
Economía        10.5
Programación    19.0
dtype: float64
6.0    1
4.5    1
8.5    1
Name: count, dtype: int64
4.5
8.5
6.333333333333333
2.0207259421636903
count    3.000000
mean     6.333333
std      2.020726
min      4.500000
25%      5.250000
50%      6.000000
75%      7.250000
max      8.500000
dtype: float64

## 3.9 Apply operators to series

In [21]:
import pandas as pd
s=pd.Series([1, 2, 3, 4])
print("Serie original")
print(s)
print("\nSerie s=s*2")
s=s*2
print(s)
print("\nSerie s=s%2")
s=s%2
print(s)

s=pd.Series(['a', 'b', 'c'])
print("\nSerie original")
print(s)
print("\nSerie s=s*5")
s=s*5
print(s)
#Los (+, *, /, etc.) pueden utilizarse con una serie, y devuelven otra serie con el resultado de aplicar la operación a cada elemento de la serie.

Serie original
0    1
1    2
2    3
3    4
dtype: int64

Serie s=s*2
0    2
1    4
2    6
3    8
dtype: int64

Serie s=s%2
0    0
1    0
2    0
3    0
dtype: int64

Serie original
0    a
1    b
2    c
dtype: object

Serie s=s*5
0    aaaaa
1    bbbbb
2    ccccc
dtype: object

## 3.10 Apply functions to Series

In [22]:
#La función .apply() para pandas facilita el uso de funciones personalizadas
#a DataFrames pero no es particularmente eficiente y muchas veces es mejor utilizar
#funciones nativas de pandas o numpy - ¡solo es cuestión de encontrarlas!

import pandas as pd
s=pd.Series(['a', 'b', 'c'])
print(s.str.upper())

import pandas as pd
import math
datos={'Matemáticas':6.0, 'Economía':4,'Programación': 8.5}
s=pd.Series(datos)
s.apply(math.sqrt)

0    A
1    B
2    C
dtype: object

Matemáticas     2.449490
Economía        2.000000
Programación    2.915476
dtype: float64

In [23]:
def AddHola(cadena):
    cadena=cadena + " Hola"
    return cadena

s2=pd.Series(['ana', 'borja', 'cecilia'])
print(s2)
s2.apply(AddHola)
print(s2.apply(AddHola))
s3= s2.apply(AddHola)
print(s3)

0        ana
1      borja
2    cecilia
dtype: object
0        ana Hola
1      borja Hola
2    cecilia Hola
dtype: object
0        ana Hola
1      borja Hola
2    cecilia Hola
dtype: object

## 3.11 Filtering Series

In [24]:
#Filtrado de una serie
#Para filtrar una serie y quedarse con los valores que cumplen una determinada condición se utiliza el siguiente
#método:

#s[condicion] : Devuelve una serie con los elementos de la serie s que se corresponden con el valor True de la
#lista booleana condicion. condicion debe ser una lista de valores booleanos de la misma longitud que la serie.

s=pd.Series({'Matemáticas': 6.0,  'Economía': 4.5, 'Programación': 8.5})
lista=s>5
print(lista)
print(s[lista])

Matemáticas      True
Economía        False
Programación     True
dtype: bool
Matemáticas     6.0
Programación    8.5
dtype: float64

## 3.12 Sorting

In [25]:
#Ordenar una serie.
#Para ordenar una serie se utilizan los siguientes métodos:
#1.- s.sort_values(ascending=booleano) : Devuelve la serie que resulta de ordenar los valores la serie s.
# Si argumento del parámetro ascending es True el orden es creciente y si es False decreciente.
#2.-df.sort_index(ascending=booleano) : Devuelve la serie que resulta de ordenar el índice de la serie s.
 #Si el argumento del parámetro ascending es True el orden es creciente y si es False decreciente.

import pandas as pd
s=pd.Series({'Matemáticas': 6.0,  'Economía': 4.5, 'Programación': 8.5})
print(s.sort_values())
print(s.sort_index(ascending = False))

Economía        4.5
Matemáticas     6.0
Programación    8.5
dtype: float64
Programación    8.5
Matemáticas     6.0
Economía        4.5
dtype: float64

# 4 Dataframes
A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

Un objeto del tipo DataFrame define un conjunto de datos estructurado en forma de tabla donde cada columna es un objeto de tipo Series, es decir, todos los datos de una misma columna son del mismo tipo, y las filas son registros que pueden contender datos de distintos tipos.
Un DataFrame contiene dos índices, uno para las filas y otro para las columnas, y se puede acceder a sus elementos mediante los nombres de las filas y las columnas.
Ejemplo. El siguiente DataFrame contiene información sobre los alumnos de un curso. Cada fila corresponde a un alumno y cada columna a una variable.

# 4.1 Simple Dataframe creation

In [59]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

print(data)

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

{'calories': [420, 380, 390], 'duration': [50, 40, 45]}
   calories  duration
0       420        50
1       380        40
2       390        45

In [27]:
portfolios = pd.DataFrame(
    [[ 75,  75, 100,   0,   0],
     [  0, 100,   0,   0, 150],
     [  0,  50,   0, 100, 100]],
    index=['portfolio A', 'portfolio B', 'portfolio C'],
    columns=['apple', 'amazon', 'boeing', 'citigroup', 'walmart'])

portfolios

             apple  amazon  boeing  citigroup  walmart
portfolio A     75      75     100          0        0
portfolio B      0     100       0          0      150
portfolio C      0      50       0        100      100

## 4.2 From a dictionary

In [28]:
import pandas as pd
datos = {'nombre':['María', 'Luis', 'Carmen', 'Antonio'], 'edad':[18, 22, 20, 21],
         'grado':['Economía', 'Medicina','Arquitectura', 'Economía'],
         'correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com']}
df = pd.DataFrame(datos)
print(df)

    nombre  edad         grado             correo
0    María    18      Economía    maria@gmail.com
1     Luis    22      Medicina      luis@yahoo.es
2   Carmen    20  Arquitectura   carmen@gmail.com
3  Antonio    21      Economía  antonio@gmail.com

In [29]:
import pandas as pd
datos = {'nombre':['María', 'Luis', 'Carmen', 'Antonio'], 'edad':[18, 22, 20, 21],
         'grado':['Economía', 'Medicina','Arquitectura', 'Economía'],
         'correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com']}
indice=["fila1", "fila2", "fila3", "fila4"]
df = pd.DataFrame(datos, index=indice)
print(df)

        nombre  edad         grado             correo
fila1    María    18      Economía    maria@gmail.com
fila2     Luis    22      Medicina      luis@yahoo.es
fila3   Carmen    20  Arquitectura   carmen@gmail.com
fila4  Antonio    21      Economía  antonio@gmail.com

In [30]:
#Falla porque ya utilizaría la clave del diccionario como nombre de columna

import pandas as pd
datos = {'nombre':['María', 'Luis', 'Carmen', 'Antonio'], 'edad':[18, 22, 20, 21],
         'grado':['Economía', 'Medicina','Arquitectura', 'Economía'],
         'correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com']}
indice=["fila1", "fila2", "fila3", "fila4"]
columnas=["NOMBRE", "EDAD", "ASIGNATURA", "EMAIL"]
df = pd.DataFrame(datos, index=indice, columns=columnas)
print(df)

      NOMBRE EDAD ASIGNATURA EMAIL
fila1    NaN  NaN        NaN   NaN
fila2    NaN  NaN        NaN   NaN
fila3    NaN  NaN        NaN   NaN
fila4    NaN  NaN        NaN   NaN

## 4.3 List of dictionaries and List os lists

In [31]:
import pandas as pd
alumnos = {
    "Nombre": ["Pepe Luis", "Alejandro García","Cristina Puente", "Carlos Vallez" ],
    "Edad" : [32, 55, 20, 43]
}
alumnos

{'Nombre': ['Pepe Luis',
  'Alejandro García',
  'Cristina Puente',
  'Carlos Vallez'],
 'Edad': [32, 55, 20, 43]}

In [32]:
df2=pd.DataFrame(alumnos)
df2

             Nombre  Edad
0         Pepe Luis    32
1  Alejandro García    55
2   Cristina Puente    20
3     Carlos Vallez    43

In [33]:
import pandas as pd
datos=[{"Banco":"CAJASUR", "Cuenta":"1234567", "Saldo": 1569.23},
       {"Banco":"BBVA", "Cuenta":"545367", "Saldo": 4169.54},
       {"Banco":"BS", "Cuenta":"3437", "Saldo": 8176.54}]
data_frame = pd.DataFrame(data=datos)
data_frame

     Banco   Cuenta    Saldo
0  CAJASUR  1234567  1569.23
1     BBVA   545367  4169.54
2       BS     3437  8176.54

In [34]:
#A las columnas se le han dado nombres  numéricos basados en la posición de los datos en las listas
import pandas as pd
datos=[["Pepe", 1258.45, 629711699],
      ["Juan", 565.36, 914748638],
      ["Alfredo", 58859.88, 629065896]]
data_frame=pd.DataFrame(data=datos)
print(data_frame)

         0         1          2
0     Pepe   1258.45  629711699
1     Juan    565.36  914748638
2  Alfredo  58859.88  629065896

In [35]:
datos=[["Pepe", 1258.45, 629711699],
      ["Juan", 565.36, 914748638],
      ["Alfredo", 58859.88, 629065896]]
nombres_col=["Nombres", "Salario", "Teléfono"]
data_frame=pd.DataFrame(data=datos, columns=nombres_col)
print(data_frame)

   Nombres   Salario   Teléfono
0     Pepe   1258.45  629711699
1     Juan    565.36  914748638
2  Alfredo  58859.88  629065896

In [36]:
datos=[["Pepe", 1258.45, 629711699],
      ["Juan", 565.36, 914748638],
      ["Alfredo", 58859.88, 629065896]]
nombres_col=["Nombres", "Salario", "Teléfono"]
nombres_fil=["fila1", "fila2", "fila3"]
data_frame=pd.DataFrame(data=datos, index=nombres_fil,columns=nombres_col)
print(data_frame)
data_frame

       Nombres   Salario   Teléfono
fila1     Pepe   1258.45  629711699
fila2     Juan    565.36  914748638
fila3  Alfredo  58859.88  629065896

       Nombres   Salario   Teléfono
fila1     Pepe   1258.45  629711699
fila2     Juan    565.36  914748638
fila3  Alfredo  58859.88  629065896

## 4.4 From CSV files

In [37]:
import pandas as pd

df = pd.read_csv('country.csv', encoding='latin1')

df

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Inflation,Official name of Country
0,Afghanistan,Kabul,652 090,29.12,2.58%,Afghani,Not known,Islamic State of Afghanistan
1,Algeria,Alger,2 381 741,34.3,1.20%,Dinar,Not known,People's Democratic Republic of Algeria
2,Angola,Luanda,1 246 700,18.99,2.10%,Kwanza,Not known,Republic of Angola
3,Antigua and Barbuda,Saint Johns,440,0.09,1.30%,E.C. Dollar,Not known,NaN
4,Argentina,Buenos Aires,2 766 890,40.09,1.05%,Peso,Not known,Argentine Republic
...,...,...,...,...,...,...,...,...
130,Western Sahara,No Capital,266 000,0.53,2.83%,Not known,Not known,NaN
131,Vietnam,Hanoi,329 566,86.93,1.14%,Dong,Not known,Socialist Republic of Viet Nam
132,Yemen,San'a,531 869,22.49,2.79%,Rial,Not known,Republic of Yemen
133,Zambia,Lusaka,752 614,13.05,1.63%,Kwacha,Not known,Republic of Zambia
134,Zimbabwe,Harare,390 759,12.64,1.53%,Dollar,Not known,Republic of Zimbabwe

In [38]:
#use to_string() to print the entire DataFrame.
print(df.to_string())

                              Country              Capital Area(km.sq) Population(mio) Pop. Growth     Currency  Inflation                         Official name of Country
0                         Afghanistan                Kabul    652 090            29.12       2.58%      Afghani  Not known                     Islamic State of Afghanistan
1                             Algeria                Alger   2 381 741            34.3       1.20%        Dinar  Not known          People's Democratic Republic of Algeria
2                              Angola               Luanda   1 246 700           18.99       2.10%       Kwanza  Not known                               Republic of Angola
3                 Antigua and Barbuda          Saint Johns         440            0.09       1.30%  E.C. Dollar  Not known                                              NaN
4                           Argentina         Buenos Aires  2 766 890            40.09       1.05%         Peso  Not known                               Argentine Republic
5                             Bahamas               Nassau      13 940            0.35       0.93%       Dollar  Not known                      Commonwealth of the Bahamas
6                             Bahrain           Al Manamah         622            0.81       1.29%        Dinar  Not known                                 State of Bahrain
7                          Bangladesh                Dhaka    143 999            150.1       1.29%         Taka  Not known                  People's Republic of Bangladesh
8                              Belize             Belmopan      22 960            0.33       2.15%       Dollar  Not known                                              NaN
9                               Benin           Porto-Novo     112 622            8.52       2.98%    CFA-Franc  Not known                                Republic of Benin
10                             Bhutan               Thimpu     46 500              0.7       1.27%     Ngultrum  Not known                                Kingdom of Bhutan
11                            Bolivia               La Paz   1 098 580           10.43       1.77%    Boliviano  Not known                              Republic of Bolivia
12                           Botswana             Gaborone     582 000             1.8       1.94%         Pula  Not known                             Republic of Botswana
13                             Brunei  Bandar Seri Begawan      5 765             0.41       1.76%       Dollar  Not known                                Brunei Darussalam
14                       Burkina Faso          Ouagadougou     274 122           15.73       3.10%    CFA-Franc  Not known                                              NaN
15                              Burma            Naypyidaw    676 577             50.5       0.78%         Kyat  Not known                                 Union of Myanmar
16                            Burundi            Bujumbura      27 834            8.52       3.69%        Franc  Not known                              Republic of Burundi
17                           Cambodia           Phnom-Penh    181 035             13.4       1.77%         Riel  Not known                              Kingdom of Cambodia
18                           Cameroon              Yaounde     475 442           19.41       2.19%    CFA-Franc  Not known                             Republic of Cameroon
19           Central African Republic               Bangui     622 984            4.51       1.49%    CFA-Franc  Not known                                              NaN
20                              Chile             Santiago     756 950           17.19       0.88%         Peso  Not known                                Republic of Chile
21                              China               Peking  9 596 961         1 342.49       0.47%         Yuan  Not known                       People's Republic of China
22                           Colombia               Bogota   1 138 910           45.86       1.22%         Peso  Not known                             Republic of Colombia
23          Congo Democratic Republic             Kinshasa   2 344 885           67.83       3.21%        Zaire  Not known                 Democratic Republic of the Congo
24                     Congo Republic          Brazzaville     342 000            3.76       2.75%    CFA-Franc  Not known                            Republic of the Congo
25                         Costa Rica             San Jose      51 100            4.56       1.36%        Colon  Not known                           Republic of Costa Rica
26                               Cuba              Havanna     110 860           11.24       0.23%         Peso  Not known                                 Republic of Cuba
27                             Cyprus              Nicosia      9 251              0.8       1.69%        Pound  Not known                               Republic of Cyprus
28                           Djibouti             Djibouti      23 200            0.88       2.16%        Franc  Not known                             Republic of Djibouti
29                           Dominica               Roseau         750            0.07       0.21%  E.C. Dollar  Not known                         Commonwealth of Dominica
30                 Dominican Republic        Santo Domingo      48 730            9.88       1.49%      RD-Peso  Not known                               Dominican Republic
31                            Ecuador                Quito     283 560           14.31       1.50%        Sucre  Not known                              Republic of Ecuador
32                              Egypt                Cairo   1 001 449           79.84       2.03%        Pound  Not known                           Arab Republic of Egypt
33                        El Salvador         San Salvador      21 040            6.19       1.66%        Colon  Not known                          Republic of El Salvador
34                  Equatorial Guinea                Malbo      28 051            0.69       2.70%    CFA-Franc  Not known                    Republic of Equatorial Guinea
35                            Eritrea               Asmara     125 000            5.22       2.58%         Birr  Not known                                              NaN
36                           Ethiopia          Addis Abeba   1 241 000           79.46       3.21%         Birr  Not known          Federal Democratic Republic of Ethiopia
37                               Fiji                 Suva      18 376            0.85       1.38%       Dollar  Not known                                 Republic of Fiji
38                      French Guyana               Cyenne      91 000       Not known   Not known         Euro  Not known                                              NaN
39                              Gabon           Libreville     267 667             1.5       1.93%    CFA-Franc  Not known                                Gabonese Republic
40                             Gambia               Banjul      11 295            1.75       2.59%       Dalasi  Not known                           Republic of the Gambia
41                              Ghana                Accra     238 537           24.23       1.90%     New Cedi  Not known                                Republic of Ghana
42                            Grenada       Saint George´s         340             0.1       0.47%  E.C. Dollar  Not known                                              NaN
43                         Guadeloupe          Basse Terre       1 780           14.36   Not known         Euro  Not known                                              NaN
44                          Guatemala            Guatemala     108 890           10.32       2.07%      Quetzal  Not known                            Republic of Guatemala
45                             Guinea              Conakry     245 857            1.65       2.57%        Franc  Not known                               Republic of Guinea
46                      Guinea-Bissau               Bissau      36 125            0.78       2.02%         Peso  Not known                        Republic of Guinea-Bissau
47                             Guyana          George Town     214 970       Not known      -0.63%       Dollar  Not known                   Cooperative Republic of Guyana
48                              Haiti       Port Au Prince      27 750           10.09       1.84%       Guorde  Not known                                Republic of Haiti
49                           Honduras          Tegucigalpa     112 090            7.62          2%      Lempira  Not known                             Republic of Honduras
50                              India            New Delhi  3 166 829         1 194.43       1.41%        Rupee  Not known                                Republic of India
51                          Indonesia              Jakarta  1 191 443           237.56       1.14%       Rupiah  Not known                            Republic of Indonesia
52                               Iran               Tehran  1 648 100            75.08       0.88%         Rial  Not known                         Islamic Republic of Iran
53                               Iraq              Baghdad    434 924            31.47       2.51%        Dinar  Not known                                 Republic of Iraq
54                             Israel            Jerusalem     20 770              7.7       1.67%      Sheckel  Not known                                  State of Israel
55                        Ivory Coast         Yamoussoukro     322 463           21.57       2.13%    CFA-Franc  Not known                        Republic of Côte d'Ivoire
56                            Jamaica             Kingston      10 490            2.73       0.76%       Dollar  Not known                                              NaN
57                             Jordan                Amman     97 740             6.47       2.19%        Dinar  Not known                      Hashemite Kingdom of Jordan
58                              Kenya              Nairobi    582 646            38.61       2.69%     Shilling  Not known                                Republic of Kenya
59                           Kiribati              Bairiki         861             0.1       2.24%   Aus Dollar  Not known                                              NaN
60                             Kuwait               Kuwait     17 818             3.05       3.55%        Dinar  Not known                                  State of Kuwait
61                         Kyrgyzstan              Bisjkek    198 500             5.42       1.40%          Som  Not known                                 Kyrghyz Republic
62                               Laos            Vientiane    236 800             6.23       2.32%          Kip  Not known                 Lao People's Democratic Republic
63                            Lebanon               Beirut     10 452             4.25       1.11%        Pound  Not known                                Lebanese Republik
64                            Lesotho               Maseru      30 355            2.08       0.12%         Loti  Not known                               Kingdom of Lesotho
65                            Liberia             Monrovia     111 370             4.1       2.67%       Dollar  Not known                              Republic of Liberia
66                              Libya              Tripoli   1 759 540            6.55       2.17%        Dinar  Not known  Great Socialist People's Libyan Arab Jamahiriya
67                         Madagascar           Antanarivo     587 041           20.15          3%        Franc  Not known                           Republic of Madagascar
68                             Malawi             Lilongwe     118 484           15.69       2.75%       Kwacha  Not known                               Republic of Malawi
69                           Maldives                 Malé         298            0.32      -0.17%      Rufiyaa  Not known                             Republic of Maldives
70                               Mali               Bamako   1 240 192           14.52       2.59%    CFA-Franc  Not known                                 Republic of Mali
71                   Marshall Islands               Majuro         181            0.05       2.08%    US Dollar  Not known                     Republic of Marshall Islands
72                         Martinique       Fort-De-France       1 100       Not known   Not known         Euro  Not known                                              NaN
73                         Mauritania            Nouachott   1 030 700            3.37       2.40%      Ouguiya  Not known                   Islamic Republic of Mauritania
74                          Mauritius           Port Louis       2 040            1.28       0.78%        Rupee  Not known                            Republic of Mauritius
75                             Mexico          Mexico City  1 973 000           112.32       1.13%         Peso  Not known                            United Mexican States
76                         Micronesia              Kolonia         702             0.1      -0.24%    US Dollar  Not known                   Federated States of Micronesia
77                           Mongolia           Ulan Bator  1 565 000             2.79       1.49%      Tughrik  Not known                                              NaN
78                            Morocco                Rabat     458 730           32.07       1.10%       Dirham  Not known                               Kingdom of Morocco
79                         Mozambique               Maputo     799 380           22.42       1.79%      Metical  Not known                           Republic of Mozambique
80                            Namibia             Windhoek     824 292            2.21       0.95%      SA Rand  Not known                              Republic of Namibia
81                              Nauru           No Capital        21.3            0.01       1.75%   Aus Dollar  Not known                                Republic of Nauru
82                              Nepal            Kathmandu    147 181            28.58       1.28%        Rupee  Not known                                 Kingdom of Nepal
83                        New Zealand           Wellington    269 000              4.4       0.94%       Dollar  Not known                                              NaN
84                          Nicaragua              Managua     129 490            5.82       1.78%  New Córdoba  Not known                            Republic of Nicaragua
85                              Niger               Niamey   1 267 000            15.2       3.68%    CFA-Franc  Not known                                Republic of Niger
86                            Nigeria                Lagos     923 768          158.26          2%        Naira  Not known                      Federal Republic of Nigeria
87                        North Korea           P'yongyang    120 538            23.99       0.42%          Won  Not known            Democratic People's Republic of Korea
88                               Oman               Masqat    300 000             2.69       3.14%         Rial  Not known                                Sultanate of Oman
89                           Pakistan              Karachi    803 943           171.91       1.56%        Rupee  Not known                     Islamic Republic of Pakistan
90                             Panama               Panama      78 200            3.41       1.50%       Balboa  Not known                               Republic of Panama
91                   Papua New Guinea         Port Moresby     462 840            6.89       2.09%         Kina  Not known                                              NaN
92                           Paraguay             Asuncion     406 750            6.46       2.36%      Guarani  Not known                             Republic of Paraguay
93                               Peru                 Lima   1 285 220           29.46       1.23%         Inti  Not known                                 Republic of Peru
94                        Philippines               Manila    300 000            94.01       1.96%         Peso  Not known                      Republic of the Philippines
95                              Qatar            Al Dawhah     11 437              1.7       0.96%        Riyal  Not known                                   State of Qatar
96                             Rwanda               Kigali      26 383           10.41       2.87%        Franc  Not known                                Rwandese Republic
97              Saint Kitts and Nevis          Basse Terre         269            0.05       0.85%  E.C. Dollar  Not known                                              NaN
98                        Saint Lucia             Lastries         620            0.17       0.42%  E.C. Dollar  Not known                                              NaN
99   Saint Vincent and the Grenadines            Kingstown         340            0.11      -0.34%  E.C. Dollar  Not known                                              NaN
100                      Saudi Arabia               Riyadh  2 240 000            27.14       1.85%        Riyal  Not known                          Kingdom of Saudi Arabia
101                           Senegal                Dakar     196 192           12.86       2.71%    CFA-Franc  Not known                              Republic of Senegal
102                      Sierra Leone             Freetown      71 740            5.84       2.18%        Leone  Not known                         Republic of Sierra Leone
103                   Solomon Islands              Honiara      27 556            0.53       2.39%       Dollar  Not known                                              NaN
104                           Somalia            Mogadishu     637 657            9.36       2.82%     Shilling  Not known                       Somali Democratic Republic
105                      South Africa             Pretoria  1 221 000            49.99       0.28%      SA Rand  Not known                         Republic of South Africa
106                       South Korea                Seoul     99 022            48.99       0.27%          Won  Not known                                Republic of Korea
107                         Sri Lanka              Colombo     65 610            20.41       0.90%        Rupee  Not known       Democratic Socialist Republic of Sri Lanka
108                             Sudan             Khartoum   2 505 813           43.19       2.14%        Pound  Not known                                Republic of Sudan
109                          Suriname           Paramaribo     163 270            0.52       1.10%       Gulden  Not known                             Republic of Suriname
110                         Swaziland              Mbabane      17 363             1.2       1.31%    Lilangeni  Not known                             Kingdom of Swaziland
111                             Syria             Damascus    185 180            20.94       2.01%        Pound  Not known                             Syrian Arab Republic
112                            Taiwan               Taipei     39 179            23.16       0.23%       Dollar  Not known                                              NaN
113                        Tajikistan             Dusjanbe    143 000             7.07       1.88%         Rubl  Not known                           Republic of Tajikistan
114                          Tanzania        Dar es Salaam     945 087           43.19       2.04%     Shilling  Not known                      United Republic of Tanzania

1.- read_csv(fichero.csv, sep=separador, header=n, index_col=m, na_values=no-validos, decimal=separador-decimal) : Devuelve un objeto del tipo DataFrame con los datos del fichero CSV fichero.csv usando como separador de los datos la cadena separador.
Como nombres de columnas se utiliza los valores de la fila n y como nombres de filas los valores de la columna m. Si no se indica m se utilizan como nombres de filas los enteros empezando en 0. Los valores incluídos en la lista no-validos se convierten en NaN. Para los datos numéricos se utiliza como separador de decimales el carácter indicado en separador-decimal.

No poner nada es lo mismo que poder header=0
Si no ponemos el atributo index_col  numera las filas empezando en 0

<https://www.w3schools.com/python/pandas/pandas_csv.asp>

## 4.5 From Other files

- CSV format: [read_csv()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)
- Excel spreasheet: [read_excel()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html)
- JSON format: [read_json()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html)

In [39]:
import pandas as pd

df4 = pd.read_json('data.json')
df4

FileNotFoundError: File data.json does not exist

Investigate:

2 json

<https://www.w3schools.com/python/pandas/pandas_json.asp>

3.- read_excel(fichero.xlsx, sheet_name=hoja, header=n, index_col=m, na_values=no-validos, decimal=separador-decimal) : Devuelve un objeto del tipo DataFrame con los datos de la hoja de cálculo hoja del fichero Excel fichero.xlsx. Como nombres de columnas se utiliza los valores de la fila n y como nombres de filas los valores de la columna m. Si no se indica m se utilizan como nombres de filas los enteros empezando en 0. Los valores incluídos en la lista no-validos se convierten en NaN. Para los datos numéricos se utiliza como separador de decimales el carácter indicado en separador-decimal.

## 4.6 Export a Dataframe to a file

df.to_csv(fichero.csv, sep=separador, columns=booleano, index=booleano)

df.to_excel(fichero.xlsx, sheet_name = hoja, columns=booleano, index=booleano)

Investigate them.

Exportación de ficheros

También existen funciones para exportar un DataFrame a un fichero con diferentes formatos.
df.to_csv(fichero.csv, sep=separador, columns=booleano, index=booleano) : Exporta el DataFrame df al fichero fichero.csv en formato CSV usando como separador de los datos la cadena separador. Si se pasa True al parámetro columns se exporta también la fila con los nombres de columnas y si se pasa True al parámetro index se exporta también la columna con los nombres de las filas.

df.to_excel(fichero.xlsx, sheet_name = hoja, columns=booleano, index=booleano) : Exporta el DataFrame df a la hoja de cálculo hoja del fichero fichero.xlsx en formato Excel. Si se pasa True al parámetro columns se exporta también la fila con los nombres de columnas y si se pasa True al parámetro index se exporta también la columna con los nombres de las filas.

## 4.7 Dataframes Attributes

Atributos de un DataFrame   
Existen varias propiedades o métodos para ver las características de un DataFrame.    
df.info() : Devuelve información (número de filas, número de columnas, índices, tipo de las columnas y memoria usado) sobre el DataFrame df.    
df.shape : Devuelve una tupla con el número de filas y columnas del DataFrame df.   
df.size : Devuelve el número de elementos del DataFrame.  
df.columns : Devuelve una lista con los nombres de las columnas del DataFrame df.   
df.index : Devuelve una lista con los nombres de las filas del DataFrame df.    
df.dtypes : Devuelve una serie con los tipos de datos de las columnas del DataFrame df.   
df.head(n) : Devuelve las n primeras filas del DataFrame df.    
df.tail(n) : Devuelve las n últimas filas del DataFrame df.

In [ ]:
import pandas as pd
df = pd.read_csv( 'https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nombre      14 non-null     object
 1   edad        14 non-null     int64
 2   sexo        14 non-null     object
 3   peso        13 non-null     float64
 4   altura      14 non-null     float64
 5   colesterol  13 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 800.0+ bytes

In [ ]:
df.shape

(14, 6)

In [ ]:
df.size

84

In [ ]:
df.columns

Index(['nombre', 'edad', 'sexo', 'peso', 'altura', 'colesterol'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=14, step=1)

In [ ]:
df.dtypes

nombre         object
edad            int64
sexo           object
peso          float64
altura        float64
colesterol    float64
dtype: object

## 4.8 Rename rows and columns

NO ES INPLACE
Renombrar los nombres de las filas y columnas
Para cambiar el nombre de las filas y las columnas de un DataFrame se utiliza el siguiente método:

df.rename(columns=columnas, index=filas): Devuelve el DataFrame que resulta de renombrar las columnas indicadas en las claves del diccionario columnas con sus valores y las filas indicadas en las claves del diccionario filas con sus valores en el DataFrame df.

In [ ]:

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv')

print(df)

df2=df.rename(columns={'nombre':'nombre y apellidos', 'altura':'estatura'}, index={0:1000, 1:1001, 2:1002})

In [ ]:
df2

## 4.9 Reindex a Dataframe

NO ES INPLACE

Reindexar un DataFrame
Para reordenar los índices de las filas y las columnas de un DataFrame, así como añadir o eliminar índices, se utiliza el siguiente método:
df.reindex(index=filas, columns=columnas, fill_value=relleno) :

Devuelve el DataFrame que resulta de tomar del DataFrame df las filas con nombres en la lista filas y las columnas con nombres en la lista columnas. Si alguno de los nombres indicados en filas o columnas no existía en el DataFrame df, se crean filan o columnas nuevas rellenas con el valor relleno.

In [ ]:

import pandas as pd
df = pd.read_csv( 'https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv')
df3= df.reindex(index=[4, 3, 1], columns=['nombre', 'tensión', 'colesterol'])

In [ ]:
df

In [ ]:
df3

## 4.10 Accesing to the Dataframe elements

1.- Mediante posiciones
1.- df.iloc[i, j] : Devuelve el elemento que se encuentra en la fila i y la columna j del DataFrame df. Pueden indicarse secuencias de índices para obtener partes del DataFrame.

2.-df.iloc[filas, columnas] : Devuelve un DataFrame con los elementos de las filas de la lista filas y de las columnas de la lista columnas.

3.- df.iloc[i] : Devuelve una serie con los elementos de la fila i del DataFrame df.
 los datos de un DataFrame se puede hacer a través de posiciones o través de los nombres de las filas y columnas.

2.- Mediante nombres
df.loc[fila, columna] : Devuelve el elemento que se encuentra en la fila con nombre fila y la columna de con nombre columna del DataFrame df.
df.loc[filas, columnas] : Devuelve un DataFrame con los elemento que se encuentra en las filas con los nombres de la lista filas y las columnas con los nombres de la lista columnas del DataFrame df.

df[columna] : Devuelve una serie con los elementos de la columna de nombre columna del DataFrame df.

df.columna : Devuelve una serie con los elementos de la columna de nombre columna del DataFrame df. Es similar al método anterior pero solo funciona cuando el nombre de la columna no tiene espacios en blanco.

### 4.10.1 Examples iloc

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv")
print(df)

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
import pandas as pd
df = pd.read_csv(
"https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv")
print(df.iloc[1, 3])

65.0

In [ ]:
print(df.iloc[1, :2])

nombre    Rosa Díaz Díaz
edad                  32
Name: 1, dtype: object

In [ ]:
print(df.iloc[0])

nombre        José Luis Martínez Izquierdo
edad                                    18
sexo                                     H
peso                                  85.0
altura                                1.79
colesterol                           182.0
Name: 0, dtype: object

In [ ]:
lista_filas=[0, 2]
print(df.iloc[lista_filas])

                         nombre  edad sexo  peso  altura  colesterol
0  José Luis Martínez Izquierdo    18    H  85.0    1.79       182.0
2         Javier García Sánchez    24    H   NaN    1.81       191.0

In [ ]:
lista_filas=[0, 2]
lista_columnas=[0,3]
print(df.iloc[lista_filas, lista_columnas])

                         nombre  peso
0  José Luis Martínez Izquierdo  85.0
2         Javier García Sánchez   NaN

### 4.10.2 Examples loc

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv")
print(df)

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
df.loc[2,"colesterol"]

191.0

In [ ]:
df5= df.loc[:3,["colesterol", "peso"]]

In [ ]:
df5

   colesterol  peso
0       182.0  85.0
1       232.0  65.0
2       191.0   NaN
3       200.0  65.0

## 4.11 Indexing with logical expressions

In [ ]:
df.edad>50

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7     False
8     False
9     False
10     True
11     True
12    False
13    False
Name: edad, dtype: bool

In [ ]:
indice=df.edad>50
df6=df[indice]
df6

                        nombre  edad sexo  peso  altura  colesterol
5            Antonio Ruiz Cruz    68    H  66.0    1.74       249.0
6      Antonio Fernández Ocaña    51    H  62.0    1.72       276.0
10       Macarena Álvarez Luna    53    M  55.0    1.62       262.0
11  José María de la Guía Sanz    58    H  78.0    1.87       198.0

In [ ]:
indice2=(df.edad>50) &(df.altura<1.75)
df7=df[indice2]
df7

                     nombre  edad sexo  peso  altura  colesterol
5         Antonio Ruiz Cruz    68    H  66.0    1.74       249.0
6   Antonio Fernández Ocaña    51    H  62.0    1.72       276.0
10    Macarena Álvarez Luna    53    M  55.0    1.62       262.0

### 4.11.1 Accesing using [ ] or .

Si accedo a través de la sintaxis “.” el nombre no puede contener espacios en blanco o guiones

In [ ]:

clientes = {
    "Banco": ["IBERCAJA", "Banco Santander","BBVA" ],
    "NºCuenta" : ["32zer4", "34uhg4","23V5DFD"],
    "Saldo":[3568.23, 5685.25, 869.235]
}
DFClientes=pd.DataFrame(data=clientes, index=['a','b','c'])
print(DFClientes)

In [ ]:
DFClientes["Banco"]

In [ ]:
DFClientes.Banco

In [ ]:
DFClientes[["Saldo","Banco"]]

In [ ]:
DFClientes[0:2]

In [ ]:
DFClientes[[True, False, True]]

In [ ]:
indice2=(df.edad>50) &(df.altura<1.75)
df8=df[(df["edad"]>50) & (df["altura"]<1.75)]
df8

In [ ]:
df

In [ ]:
milista=[20,22,24]
df9= df[(df["sexo"]=='M') & df["edad"].isin(milista)]
df9

### 4.11.2 remember the usue of iloc and loc

iloc to access by index   
loc to access by name

In [ ]:
df

In [ ]:
df.iloc[0,4]

In [ ]:
df.iloc[0:4,[0,2]]

In [ ]:
DFClientes

In [ ]:
DFClientes.loc["b"]

In [ ]:
DFClientes.loc[["a","c"]]

# 4.12 Apply functions to columns in pandas
Para aplicar funciones a todos los elementos de una columna se utiliza el siguiente método:

df[columna].apply(f) : Devuelve una serie con los valores que resulta de aplicar la función f a los elementos de la columna con nombre columna del DataFrame df.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv")
df

In [ ]:
def doble(valor):
    return 2*valor

In [ ]:
df["dobledeedad"]= df["edad"].apply(doble)

In [ ]:
df

,nombre,edad,sexo,peso,altura,colesterol,dobledeedad
0,José Luis Martínez Izquierdo,18,H,85.0,1.79,182.0,36
1,Rosa Díaz Díaz,32,M,65.0,1.73,232.0,64
2,Javier García Sánchez,24,H,NaN,1.81,191.0,48
3,Carmen López Pinzón,35,M,65.0,1.70,200.0,70
4,Marisa López Collado,46,M,51.0,1.58,148.0,92
5,Antonio Ruiz Cruz,68,H,66.0,1.74,249.0,136
6,Antonio Fernández Ocaña,51,H,62.0,1.72,276.0,102
7,Pilar Martín González,22,M,60.0,1.66,NaN,44
8,Pedro Gálvez Tenorio,35,H,90.0,1.94,241.0,70
9,Santiago Reillo Manzano,46,H,75.0,1.85,280.0,92
10,Macarena Álvarez Luna,53,M,55.0,1.62,262.0,106
11,José María de la Guía Sanz,58,H,78.0,1.87,198.0,116
12,Miguel Angel Cuadrado Gutiérrez,27,H,109.0,1.98,210.0,54
13,Carolina Rubio Moreno,20,M,61.0,1.77,194.0,40

### 4.12.1 Passing arguments

In [ ]:
def multiplicador(valor, multiplicando):
    return valor*multiplicando

In [ ]:
df['otracolumna'] = df.apply(lambda x: multiplicador(x['edad'], 5), axis=1)

In [ ]:
df['edadxpeso'] = df.apply(lambda x: multiplicador(x['edad'], x['peso']), axis=1)

In [ ]:
df

## 4.13 Transform column to datetime
Convertir una columna al tipo datetime
A menudo una columna contiene cadenas que representan fechas. Para convertir estas cadenas al tipo datetime se utiliza el siguiente método:

to_datetime(columna, formato): Devuelve la serie que resulta de convertir las cadenas de la columna con el nombre columna en fechas del tipo datetime con el formado especificado en formato. ( Ver librería datetime)

In [ ]:
import pandas as pd
df = pd.DataFrame({'Name': ['María', 'Carlos', 'Carmen'], 'Nacimiento':['05-03-2000', '20-05-2001', '10-12-1999']})
print(pd.to_datetime(df.Nacimiento, format = '%d-%m-%Y'))

## 4.14 Remove columns

del d[nombre] : Elimina la columna con nombre nombre del DataFrame df.

df.pop(nombre) : Elimina la columna con nombre nombre del DataFrame df y la devuelve como una serie.

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv')
edad = df.pop('edad')
print(df)
print(edad)

In [ ]:
del df["sexo"]

In [ ]:
df

In [ ]:
df.drop(columns = ["peso", "altura"])

## 4.15 Order Dataframe

In [ ]:
df.sort_values("colesterol", ascending=False)

In [ ]:
#delete rows with NaN

df.dropna()

## 4.16 Dataframes methods

Resumen descriptivo de un DataFrame   
Al igual que para las series, los siguientes métodos permiten resumir la información de un DataFrame por columnas:  
df.count() : Devuelve una serie número de elementos que no son nulos ni NaN en cada columna del DataFrame df.   
df.sum() : Devuelve una serie con la suma de los datos de las columnas del DataFrame df cuando los datos son de un tipo numérico, o la concatenación de ellos cuando son del tipo cadena str.   
df.cumsum() : Devuelve un DataFrame con la suma acumulada de los datos de las columnas del DataFrame df cuando los datos son de un tipo numérico.    
df.min() : Devuelve una serie con los menores de los datos de las columnas del DataFrame df.   
df.max() : Devuelve una serie con los mayores de los datos de las columnas del DataFrame df.   
df.mean() : Devuelve una serie con las media de los datos de las columnas del DataFrame df cuando los datos son de un tipo numérico.    
df.std() : Devuelve una serie con las desviaciones típicas de los datos de las columnas del DataFrame df cuando los datos son dfiltroe un tipo numérico.    
df.describe(include = tipo) : Devuelve un DataFrame con un resumen estadístico de las columnas del DataFrame df del tipo tipo. Para los datos numéricos (number) se calcula la media, la desviación típica, el mínimo, el máximo y los cuartiles de las columnas numéricas. Para los datos no numéricos (object) se calcula el número de valores, el número de valores distintos, la moda y su frecuencia. Si no se indica el tipo solo se consideran las columnas numéricas.    


1. Aggregating and summarizing
Once you have your data in a DataFrame, you will want to understand it's characteristics. Lets look at some of the methods that Pandas DataFrames provide for aggregating and summarizing data.
2. DataFrame methods
DataFrames have methods for getting the count of items, for getting the item that is the minimum, maximum, first or last, as well as methods to calculate the sum, product, mean, median, standard deviation, and variance.
3. Axis
All of these methods can be run across columns or rows. To specify which you would like, use the 'axis' parameter. Methods will run on rows if the parameter is set to zero, the string 'rows', or if it is omitted. To use columns, set axis to one or the string 'columns'. Lets look at examples of some of these methods.
4. Count
The count method returns the number of items. On the left you can see the original DataFrame. In this example we use the default axis setting, which counts the rows. The result is the number of rows for each column.
5. Sum
The sum method returns the result of summing items. Here, we've specified an axis value of one, to sum across the columns. So the values of all of the columns of the first row are added together with a result of four hundred fifteen and forty four cents. The other rows are calculated in the same fashion.
6. Product
The 'prod' method returns the product of items. Here we set the axis with the string 'columns', which returns the product across columns.
7. Mean
You may be familiar with the concept of a mean from statistics. It is one way to get a sense of where the center of your data lays. Pandas DataFrames offer a mean method to calculate means. Here we can see that the data in the first column averages at a higher point than the others.
8. Median
The median is calculated by ordering items by magnitude and taking the middle one. If the number of items is even, then the average of the two middle items is used. It is a useful way to see the middle of your data without distortion caused by outliers. In this example, the two middle items of the row ADD are three hundred point twenty two and three hundred one point forty nine. If we add these together and divide by two, we get three hundred point eight five five, which is the median of the column.
9. Standard deviation
The std method of a DataFrame calculates the standard deviation. This represents the amount of variation in your data. If it is small then the data is grouped together, and if large there is a greater spreed of values. We can see in this example that the first columns values are more tightly grouped than the other two.
10. Variance
Another way to understand the distribution of your data is to calculate the variance. This is done with the var method. Once again in this example, the distribution for the first column is tighter, so the variance is lower. The variance give us similar information as the standard deviation, but the standard deviation is easier to interpret on it's own, while the variance is more useful for use in other formulas.
11. Columns and rows
All of these methods can be run across a single row or column using the same row and column selection methods we've used before. For example, we can select the maximum value from the column AAD using the loc() operation. Or select the minimum from the first row using the iloc operation.
12. Let's practice!
You've been introduced to lots of ways to summarize and aggregate your data, lets practice using them!

## ... AND MANY OTHER FUNCTIONLITIES

# 5 General documentation
<https://pandas.pydata.org/docs/user_guide/index.html>
<https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf>

# PANDAS in 5 minutes

### Reading files

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving country.csv to country.csv

In [ ]:
import pandas as pd
df=pd.read_csv('country.csv',encoding='ISO-8859-1')
print(type(df))
df.head(2)

<class 'pandas.core.frame.DataFrame'>

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Inflation,Official name of Country
0,Afghanistan,Kabul,652 090,29.12,2.58%,Afghani,Not known,Islamic State of Afghanistan
1,Algeria,Alger,2 381 741,34.3,1.20%,Dinar,Not known,People's Democratic Republic of Algeria

#### Accessing by row number

In [ ]:
df.iloc[0:2]

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Inflation,Official name of Country
0,Afghanistan,Kabul,652 090,29.12,2.58%,Afghani,Not known,Islamic State of Afghanistan
1,Algeria,Alger,2 381 741,34.3,1.20%,Dinar,Not known,People's Democratic Republic of Algeria

#### Selecting some columns

In [ ]:
columns=["Country","Capital","Population(mio)","Pop. Growth","Official name of Country"]
df.iloc[0:2][columns]

,Country,Capital,Population(mio),Pop. Growth,Official name of Country
0,Afghanistan,Kabul,29.12,2.58%,Islamic State of Afghanistan
1,Algeria,Alger,34.3,1.20%,People's Democratic Republic of Algeria

#### Filtering by condition

In [ ]:
df["Currency"]=="Dollar"

0      False
1      False
2      False
3      False
4      False
       ...
130    False
131    False
132    False
133    False
134     True
Name: Currency, Length: 135, dtype: bool

In [ ]:
df[df["Currency"]=="Dollar"]

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Inflation,Official name of Country
5,Bahamas,Nassau,13 940,0.35,0.93%,Dollar,Not known,Commonwealth of the Bahamas
8,Belize,Belmopan,22 960,0.33,2.15%,Dollar,Not known,NaN
13,Brunei,Bandar Seri Begawan,5 765,0.41,1.76%,Dollar,Not known,Brunei Darussalam
37,Fiji,Suva,18 376,0.85,1.38%,Dollar,Not known,Republic of Fiji
47,Guyana,George Town,214 970,Not known,-0.63%,Dollar,Not known,Cooperative Republic of Guyana
56,Jamaica,Kingston,10 490,2.73,0.76%,Dollar,Not known,NaN
65,Liberia,Monrovia,111 370,4.1,2.67%,Dollar,Not known,Republic of Liberia
83,New Zealand,Wellington,269 000,4.4,0.94%,Dollar,Not known,NaN
103,Solomon Islands,Honiara,27 556,0.53,2.39%,Dollar,Not known,NaN
112,Taiwan,Taipei,39 179,23.16,0.23%,Dollar,Not known,NaN
119,Trinidad and Tobago,Port Of Spain,5 130,1.32,-0.10%,Dollar,Not known,Republic of Trinidad and Tobago
134,Zimbabwe,Harare,390 759,12.64,1.53%,Dollar,Not known,Republic of Zimbabwe

#### Add new column

In [ ]:
df["newCol"]="This is New"
df.head()

,nombre,edad,sexo,peso,altura,colesterol,dobledeedad,newCol
0,José Luis Martínez Izquierdo,18,H,85.0,1.79,182.0,36,This is New
1,Rosa Díaz Díaz,32,M,65.0,1.73,232.0,64,This is New
2,Javier García Sánchez,24,H,NaN,1.81,191.0,48,This is New
3,Carmen López Pinzón,35,M,65.0,1.70,200.0,70,This is New
4,Marisa López Collado,46,M,51.0,1.58,148.0,92,This is New

#### Remove column

In [ ]:
df.drop(columns=["Inflation"],inplace=True)
df.head()

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Official name of Country,newCol
0,Afghanistan,Kabul,652 090,29.12,2.58%,Afghani,Islamic State of Afghanistan,This is New
1,Algeria,Alger,2 381 741,34.3,1.20%,Dinar,People's Democratic Republic of Algeria,This is New
2,Angola,Luanda,1 246 700,18.99,2.10%,Kwanza,Republic of Angola,This is New
3,Antigua and Barbuda,Saint Johns,440,0.09,1.30%,E.C. Dollar,NaN,This is New
4,Argentina,Buenos Aires,2 766 890,40.09,1.05%,Peso,Argentine Republic,This is New

### Writing files with PANDAS

In [ ]:
values=[['Seat Ibiza','8349PFG','Rojo', '2016'],
            ['BMW X3','9449OTF','Azul', '2018'],
            ['Ford Focus','9339FJJ','Negro', '2017']]
header=["modelo","matricula","color","año"]
df=pd.DataFrame(values,columns=header)
df.head()

       modelo matricula  color   año
0  Seat Ibiza   8349PFG   Rojo  2016
1      BMW X3   9449OTF   Azul  2018
2  Ford Focus   9339FJJ  Negro  2017

In [ ]:
df.to_csv("coches5.csv",sep="^",index=False)