# ¡¡ANTES DE COMENZAR CAMBIA EL NOMBRE DE ESTE ARCHIVO !!

Cambia el nombre del archivo de modo que empiece con las tres siguientes letras `P1-` y vaya seguido del nombre del alumno separados de con un guión `-`. Para los espacios en blanco usar guiones bajos `_`

Ejemplo para un alumno:

`P1-Don_Quijote.pynb`

## Recuerda que la entrega debe hacerse en formato `.ipynb`

## A. EXPLORACIÓN DATAFRAME

### A1. Importación de librerías necesarias

In [165]:
# TODO
import pandas as pd

### A2. Carga del archivo 
- usa utf-8
- usa el separador adecuado

In [166]:
#TODO
df=pd.read_csv('apachelog (2).csv', sep=";", encoding='utf-8')

C:\Users\anais\AppData\Local\Temp\ipykernel_3976\3680809180.py:2: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('apachelog (2).csv', sep=";", encoding='utf-8')

### A3. Explora el dataframe

In [167]:
#TODO: 3.1. Explora el dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977769 entries, 0 to 977768
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DireccionIP  977769 non-null  object
 1   IdUsr        964783 non-null  object
 2   NombreUsr    964783 non-null  object
 3   FechaHora    964783 non-null  object
 4   MetodoHTTP   964783 non-null  object
 5   Ruta         964783 non-null  object
 6   VersionHTTP  963631 non-null  object
 7   EstadoHTTP   964783 non-null  object
 8   Bytes        964783 non-null  object
 9   Column10     2 non-null       float64
 10  Column11     1 non-null       float64
dtypes: float64(2), object(9)
memory usage: 82.1+ MB

In [168]:
df.describe()

         Column10  Column11
count    2.000000       1.0
mean   610.500000       0.0
std    292.035101       NaN
min    404.000000       0.0
25%    507.250000       0.0
50%    610.500000       0.0
75%    713.750000       0.0
max    817.000000       0.0

### A4. Muestra los valores unicos de tus columnas MetodoHTTP y EstadoHTTP
AYUDA: usa método unique

In [169]:
print(df['MetodoHTTP'].unique())
print(df['EstadoHTTP'].unique())

['GET' nan 'POST' 'HEAD']
[200.0 304.0 nan 302.0 404.0 403.0 '304' '200' '404' '302' '403'
 'p/apollo.html' 500.0 '501' 'HTTP/1.0' 501.0]

### A5. Cuenta el numero de valores diferentes de las columnas 
AYUDA: usa método nunique

In [170]:
print(df['MetodoHTTP'].nunique())
print(df['EstadoHTTP'].nunique())

3
15

### A6. Explora cuantos valores nan hay por columna
AYUDA: usa metodo isna()sum() o revisa tu exploracion del df

In [ ]:
print(df['MetodoHTTP'].isna().sum())
#print(df)

12986
                   DireccionIP IdUsr NombreUsr         FechaHora MetodoHTTP  \
0            in24.inetnebr.com     -         -   01/08/1995 0:00        GET
1              uplherc.upl.com     -         -   01/08/1995 0:00        GET
2              uplherc.upl.com     -         -   01/08/1995 0:00        GET
3              uplherc.upl.com     -         -   01/08/1995 0:00        GET
4              uplherc.upl.com     -         -   01/08/1995 0:00        GET
...                        ...   ...       ...               ...        ...
977764           www.neocom.ca     -         -  21/08/1995 19:41        GET
977765           www.neocom.ca     -         -  21/08/1995 19:42        GET
977766  mty0201.infosel.com.mx     -         -  21/08/1995 19:42        GET
977767           www.neocom.ca     -         -  21/08/1995 19:42        GET
977768  ip75.van3.pacifier.com     -         -  21/08/1995 19:42        GET

                                                   Ruta VersionHTTP  \
0       /shuttle/missions/sts-68/news/sts-68-mcc-05.txt    HTTP/1.0
1                                                     /    HTTP/1.0
2                            /images/ksclogo-medium.gif    HTTP/1.0
3                          /images/MOSAIC-logosmall.gif    HTTP/1.0
4                             /images/USA-logosmall.gif    HTTP/1.0
...                                                 ...         ...
977764                         /images/ksclogosmall.gif    HTTP/1.0
977765           /history/apollo/images/apollo-logo.gif    HTTP/1.0
977766       /history/apollo/apollo-13/images/index.gif    HTTP/1.0
977767          /history/mercury/mercury-spacecraft.txt    HTTP/1.0
977768                               /htbin/cdt_main.pl    HTTP/1.0

       EstadoHTTP    Bytes  Column10  Column11
0           200.0   1839.0       NaN       NaN
1           304.0      0.0       NaN       NaN
2           304.0      0.0       NaN       NaN
3           304.0      0.0       NaN       NaN
4           304.0      0.0       NaN       NaN
...           ...      ...       ...       ...
977764      200.0   3635.0       NaN       NaN
977765      200.0   3047.0       NaN       NaN
977766      200.0  99942.0       NaN       NaN
977767      200.0    761.0       NaN       NaN
977768      200.0   3714.0       NaN       NaN

[977769 rows x 11 columns]

### A6. RESUMEN EXPLORACION
TODO: Explica con tus palabras lo obtenido en la exploracion
- cuantas columns hay y cuales son
- cuantas filas hay y cuales son
- si existen valores nulos y donde
- cuantos valores son válidos en cada columna (non-null)
- que tipos de datos tienen las columnas

## B. LIMPIEZA DATAFRAME
- B0. Eliminamos las columnas que no contienen los datos previstos en el listado de campos
- B1. Trabajaremos SOLO con las columnas 1,4,5,6,8 y 9
- B2. Transformamos las columnas a los tipos de datos que nos interesan

In [172]:
# B0. Elimina columnas, almacena el dataframe en df_limpio y comprueba que ya no existen
df_limpio=df.drop(columns=["Column10", "Column11"])
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977769 entries, 0 to 977768
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DireccionIP  977769 non-null  object
 1   IdUsr        964783 non-null  object
 2   NombreUsr    964783 non-null  object
 3   FechaHora    964783 non-null  object
 4   MetodoHTTP   964783 non-null  object
 5   Ruta         964783 non-null  object
 6   VersionHTTP  963631 non-null  object
 7   EstadoHTTP   964783 non-null  object
 8   Bytes        964783 non-null  object
dtypes: object(9)
memory usage: 67.1+ MB

In [173]:
#B1. Haz un nuevo dataset (df_nuevo) con las columnas de trabajo 
#AYUDA: usa .iloc o .loc y crea una copia superficial
df_nuevo=df_limpio.iloc[:,[0,3,4,5,7,8]].copy()
df_nuevo

,DireccionIP,FechaHora,MetodoHTTP,Ruta,EstadoHTTP,Bytes
0,in24.inetnebr.com,01/08/1995 0:00,GET,/shuttle/missions/sts-68/news/sts-68-mcc-05.txt,200.0,1839.0
1,uplherc.upl.com,01/08/1995 0:00,GET,/,304.0,0.0
2,uplherc.upl.com,01/08/1995 0:00,GET,/images/ksclogo-medium.gif,304.0,0.0
3,uplherc.upl.com,01/08/1995 0:00,GET,/images/MOSAIC-logosmall.gif,304.0,0.0
4,uplherc.upl.com,01/08/1995 0:00,GET,/images/USA-logosmall.gif,304.0,0.0
...,...,...,...,...,...,...
977764,www.neocom.ca,21/08/1995 19:41,GET,/images/ksclogosmall.gif,200.0,3635.0
977765,www.neocom.ca,21/08/1995 19:42,GET,/history/apollo/images/apollo-logo.gif,200.0,3047.0
977766,mty0201.infosel.com.mx,21/08/1995 19:42,GET,/history/apollo/apollo-13/images/index.gif,200.0,99942.0
977767,www.neocom.ca,21/08/1995 19:42,GET,/history/mercury/mercury-spacecraft.txt,200.0,761.0
977768,ip75.van3.pacifier.com,21/08/1995 19:42,GET,/htbin/cdt_main.pl,200.0,3714.0

In [174]:
#B2. Transforma los datos de las columnas 1,4,5,6,8, y 9 en los correctos y comprueba los tipos
# - numeros: float o int
# . fechas con datetime
# - cadenas en string

In [175]:
# COLUMNAS TIPO STRING
df_nuevo['DireccionIP']=df_nuevo['DireccionIP'].fillna('').astype("string")
df_nuevo['MetodoHTTP']= df_nuevo['MetodoHTTP'].fillna('').astype("string")
df_nuevo['Ruta']=df_nuevo['Ruta'].fillna('').astype("string")
df_nuevo['EstadoHTTP']=df_nuevo['EstadoHTTP'].fillna('').astype("string")

In [176]:
# COLUMNAS FECHA
df_nuevo['FechaHora'] = pd.to_datetime(df['FechaHora'], errors='coerce')

In [177]:
# COLUMNAS NUMÉRICAS
df_nuevo['Bytes'] = pd.to_numeric(df['Bytes'], errors='coerce').astype('Int64')
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977769 entries, 0 to 977768
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DireccionIP  977769 non-null  string
 1   FechaHora    530762 non-null  datetime64[ns]
 2   MetodoHTTP   977769 non-null  string
 3   Ruta         977769 non-null  string
 4   EstadoHTTP   977769 non-null  string
 5   Bytes        964782 non-null  Int64
dtypes: Int64(1), datetime64[ns](1), string(4)
memory usage: 45.7 MB

PREGUNTA 1: ¿Aun tienes valores nulos? ¿Donde?

In [178]:
# TODO: Elimina los registros con valores nan en las columnas numericas, si existen
#AYUDA: usa df.dropna con subset
df_nuevo=df_nuevo.dropna(subset=['Bytes'])
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964782 entries, 0 to 977768
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DireccionIP  964782 non-null  string
 1   FechaHora    530761 non-null  datetime64[ns]
 2   MetodoHTTP   964782 non-null  string
 3   Ruta         964782 non-null  string
 4   EstadoHTTP   964782 non-null  string
 5   Bytes        964782 non-null  Int64
dtypes: Int64(1), datetime64[ns](1), string(4)
memory usage: 52.4 MB

PREGUNTA 2: ¿cuantos valores tiene ahora tu dataset?

### C. ESTADISTICAS
Calcula valores estadisticos de tus columnas numericas