# PANDAS in 5 minutes

### Reading files read file country.csv encoding='ISO-8859-1'

In [ ]:
import pandas as pd
df= pd.read_csv('/content/sample_data/country.csv', encoding='ISO-8859-1')
print(df.info) # Te hace un resumen cuantitativo
print(df.describe())#Con describe podremos devolver un resumen descriptivo con media, desviación, mínimo, máximo y cuartiles

<bound method DataFrame.info of                  Country       Capital Area(km.sq) Population(mio)  \
0            Afghanistan         Kabul    652 090            29.12
1                Algeria         Alger   2 381 741            34.3
2                 Angola        Luanda   1 246 700           18.99
3    Antigua and Barbuda   Saint Johns         440            0.09
4              Argentina  Buenos Aires  2 766 890            40.09
..                   ...           ...         ...             ...
130       Western Sahara    No Capital    266 000             0.53
131              Vietnam         Hanoi    329 566            86.93
132                Yemen         San'a    531 869            22.49
133               Zambia        Lusaka     752 614           13.05
134             Zimbabwe        Harare     390 759           12.64

    Pop. Growth     Currency  Inflation  \
0         2.58%      Afghani  Not known
1         1.20%        Dinar  Not known
2         2.10%       Kwanza  Not known
3         1.30%  E.C. Dollar  Not known
4         1.05%         Peso  Not known
..          ...          ...        ...
130       2.83%    Not known  Not known
131       1.14%         Dong  Not known
132       2.79%         Rial  Not known
133       1.63%       Kwacha  Not known
134       1.53%       Dollar  Not known

                    Official name of Country
0               Islamic State of Afghanistan
1    People's Democratic Republic of Algeria
2                         Republic of Angola
3                                        NaN
4                         Argentine Republic
..                                       ...
130                                      NaN
131           Socialist Republic of Viet Nam
132                        Republic of Yemen
133                       Republic of Zambia
134                     Republic of Zimbabwe

[135 rows x 8 columns]>
            Country      Capital Area(km.sq) Population(mio) Pop. Growth  \
count           135          135         135             135         135
unique          135          133         133             124         107
top     Afghanistan  Basse Terre         340             0.1       2.75%
freq              1            2           2               4           3

         Currency  Inflation      Official name of Country
count         135        135                           112
unique         65          1                           112
top     CFA-Franc  Not known  Islamic State of Afghanistan
freq           13        135                             1

#### Accessing by row number ( access to two fist rows)

In [ ]:
df.iloc[0:2]
#Con iloc imprimo de la fila 0 hasta la 1 ya que la segunda no esta contenida

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Inflation,Official name of Country
0,Afghanistan,Kabul,652 090,29.12,2.58%,Afghani,Not known,Islamic State of Afghanistan
1,Algeria,Alger,2 381 741,34.3,1.20%,Dinar,Not known,People's Democratic Republic of Algeria

#### Selecting some columns (select only 3 columns, later only 3 columns of 2 first records)

In [ ]:
df.iloc[0:2, 0:3]
#Con iloc imprimo de la fila 0 a la 1 y de la columna 0 hasta la 2

       Country Capital Area(km.sq)
0  Afghanistan   Kabul    652 090
1      Algeria   Alger   2 381 741

#### Filtering by condition. Apply a filter to a column

In [ ]:
df['Capital'] == 'Alger'
#Para filtrar elegimos una columna del df y ponemos un comparador == para comprobar si esta el valor que estamos buscando
#En este caso la Capital Alger

0      False
1       True
2      False
3      False
4      False
       ...
130    False
131    False
132    False
133    False
134    False
Name: Capital, Length: 135, dtype: bool

#### Add new column with default value

In [ ]:
df["NuevaColumna"] = "Hola mundo"
#Para crearnos una nueva columna es muy parecido al ej anterior solo que esta vez
#Asignamos el nombre que queremos para nuestra columna y le asignamos valores en este caso he puesto que tdos los indices tengan Hola mundo
df.head() #Mostramos las primeras filas
#print(df)

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Inflation,Official name of Country,NuevaColumna
0,Afghanistan,Kabul,652 090,29.12,2.58%,Afghani,Not known,Islamic State of Afghanistan,Hola mundo
1,Algeria,Alger,2 381 741,34.3,1.20%,Dinar,Not known,People's Democratic Republic of Algeria,Hola mundo
2,Angola,Luanda,1 246 700,18.99,2.10%,Kwanza,Not known,Republic of Angola,Hola mundo
3,Antigua and Barbuda,Saint Johns,440,0.09,1.30%,E.C. Dollar,Not known,NaN,Hola mundo
4,Argentina,Buenos Aires,2 766 890,40.09,1.05%,Peso,Not known,Argentine Republic,Hola mundo

#### Add new column with calculated value

In [ ]:
#El valor calculado será la concatenacion de pais y capital
df['Resumen'] = df['Country'] + '-' + df['Capital']
df.head() #Mostramos las primeras filas

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Inflation,Official name of Country,NuevaColumna,Resumen
0,Afghanistan,Kabul,652 090,29.12,2.58%,Afghani,Not known,Islamic State of Afghanistan,Hola mundo,Afghanistan-Kabul
1,Algeria,Alger,2 381 741,34.3,1.20%,Dinar,Not known,People's Democratic Republic of Algeria,Hola mundo,Algeria-Alger
2,Angola,Luanda,1 246 700,18.99,2.10%,Kwanza,Not known,Republic of Angola,Hola mundo,Angola-Luanda
3,Antigua and Barbuda,Saint Johns,440,0.09,1.30%,E.C. Dollar,Not known,NaN,Hola mundo,Antigua and Barbuda-Saint Johns
4,Argentina,Buenos Aires,2 766 890,40.09,1.05%,Peso,Not known,Argentine Republic,Hola mundo,Argentina-Buenos Aires

#### Remove column

In [ ]:
df.drop(columns=["NuevaColumna"], inplace=True)
#Con inplace true nos aseguramos de eliminar la columnal df original
df.head()#Mostramos las primeras filas

,Country,Capital,Area(km.sq),Population(mio),Pop. Growth,Currency,Inflation,Official name of Country,Resumen
0,Afghanistan,Kabul,652 090,29.12,2.58%,Afghani,Not known,Islamic State of Afghanistan,Afghanistan-Kabul
1,Algeria,Alger,2 381 741,34.3,1.20%,Dinar,Not known,People's Democratic Republic of Algeria,Algeria-Alger
2,Angola,Luanda,1 246 700,18.99,2.10%,Kwanza,Not known,Republic of Angola,Angola-Luanda
3,Antigua and Barbuda,Saint Johns,440,0.09,1.30%,E.C. Dollar,Not known,NaN,Antigua and Barbuda-Saint Johns
4,Argentina,Buenos Aires,2 766 890,40.09,1.05%,Peso,Not known,Argentine Republic,Argentina-Buenos Aires

### Writing files with PANDAS. save dataframe in a csv file

In [ ]:
#A continuación con el siguiente comando me guardaré el csv
df.to_csv("country_edit.csv", sep= "|" ,index=False)
#Por defecto se guardará en la carpeta archivos
#sep será el separador que será mostrado entre las columnas
#Index=False hará que no se guarde la columna de indices